---
title: "Replication of Study X by Sample & Sample (20xx, Psychological Science)"
author: "Replication Author[s] (contact information)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
    toc_depth: 3
---

## Introduction

Wolff et al. (2009) proposes the initiator hypothesis that states in languages with morphological case (e.g., Korean, Turkish), the external argument of a clause [i.e., the subject] must be able to self energize. This restriction results in the following contrast:
The husband surprised the wife. (Highly acceptable in English/Mandarin).
The ring surprised the wife. (Highly acceptable in English/Chinese, but significantly less natural for Korean speakers).                   (Wolff et al., 2009) 
Kim & Marsden (2026) further extends this hypothesis to psych-verbs and shows that the difference persists between the case marking (Korean) and non-case marking languages (English and Mandarin). The Initiator Hypothesis predicts Turkish speakers to align with Korean speakers since they are both case marking languages. 

This study aims to test the initiator hypothesis with Turkish speakers. Since there is no study that confirms this relative contrast replicates in a case marking language other than Korean, I will employ the Turkish translations of the material in Wolff et. al. to show that the Initiator hypothesis is relevant to Turkish, and compare the data to the Korean and English speakers in Wolff et al. (2009). Lastly, the experimental design will follow  Kim & Marsden (2026) who aimed to replicate Wolff et al. (2009) with psych verbs. 

References:
Kim, J., & Marsden, H. (2026). Cross-linguistic constraints on subjecthood in causative psych verbs: An experimental investigation of Korean, Mandarin Chinese and English. Glossa Psycholinguistics, 5(1).

Wolff, P., Jeon, G. H., & Li, Y. (2009). Causers in English, Korean, and Chinese and the individuation of events. Language and Cognition, 1(2), 167-196.


## Methods

### Power Analysis

### The statistical models used in the original studies.

Wolff et al. uses F-tests for the main effects of language and energy generation of the subjects.
Kim & Marsden (2026) use Regression coefficients in their report for main effects of subjecthood.

A power analysis for the Wolff et al. study yields an f2 = 1.185, which requires 12 participants for 80% power. 
I think this is because Wolff et al. is a multilingual study and having 18 participants per language is a small sample size that might have cause an increase in the f values.


A power analysis for Kim & Marsden (2026) has an f2 of 0.41 and this yields 22 participants for 80% power.


### Planned Sample
Wolff et al. (2009) has 18 speakers for each language (i.e., English, Mandarin, and Korean) while Kim & Marsden (2026) employs 44 Korean speakers.

Considering the previous studies and the power analysis I plan a sample size of 60 native Turkish speakers. The participants will be preselected based on whether they are native speakers and if they use Turkish in their daily lives, to eliminate any attrition and intervention bias.

### Materials

This study employs the stimuli developed for Experiment 1 by Wolff et al. (2009). The sentences in Wolff et al. (2009) will be translated into Turkish.  Wolff et al. (2009) has 30 sentences with inanimate external arguments. Half of these sentences have external arguments that are mostly able to generate their own energy, as shown in (1).

The air conditioner cooled the room. (Wolff et al., 2009)

The external arguments of the other half have external arguments that are unable to generate their own energy, (2).

The knife cut the bread. (Wolff et al., 2009)

Kim & Marsden (2026) has 32 target sentences with 16 animate and 16 inanimate external arguments. This study also has 24 filler items. 

Since I replicate the design in Kim & Marsden (2026), with the materials in Wolff et al. (2009), I will have the direct translations of the 30 sentences in Wolff et al. (2009), along with 22 filler items from Kim & Marsden (2026). There will be 52 sentences in total.

### Procedure	

In this experiment, participants are shown sentences one by one on Prolific. They rate the naturalness of sentences on a 5-point scale (0 to 4), where 4 means "completely natural" and 0 means "completely unnatural." Participants will be explicitly told to base their judgments on their linguistic intuition. The entire process should take 10–15 minutes.

### Analysis Plan

Following Kim and Marsden (2006), I will implement the model using Cumulative Link Mixed Models (CLMMs) in R. The primary fixed effect will be Condition (self-energizing vs. non-self-energizing subjects). I will use Estimated Marginal Means (EMMs) to conduct pairwise comparisons between the two conditions. I will attempt to fit the maximal model, however, if it fails to converge (as in Kim and Marsden 2006), I will simplify the model by including random slopes for items only. I will use sum-coding to assess how much each condition deviates from the average rating.

### Data cleaning

Participant data will be screened based on responses to grammatical and ungrammatical fillers. Participants will be excluded if they fail to show a clear differentiation between these categories. In addition, any participant with incomplete data or suspicious response patterns (e.g., selecting the same rating for every item) will be removed from the analysis.

### Differences from Original Study

Unlike Kim and Marsden, this study focuses on a single language (Turkish), therefore, there won’t be a group condition.
After analyzing the Turkish data, I will compare the results to the Wolff et al. study.
This will have to include some changes because Wolff et al. used a 0–100 scale and F-tests, unlike the design I am following.  Therefore, the comparison with their study will be conceptual and focus on whether Turkish speakers show a significantly larger drop in acceptability for non-initiating subjects than English or Chinese speakers, aligning with Korean speakers.


Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
